Homework 2
================
Natasha Woon
2026-10-04

Load Packages

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

Importing CSV File

``` r
subway_df = 
  read_csv(file = "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
           na = c("", "NA", ".")) |> 
  janitor::clean_names() |>
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, entrance_type, vending, ada) |>
  mutate(
    entry = recode_values(
      entry, 
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

This dataset contains data about NYC subway transit lines. The variables
include line, station_name, station_latitude, station_longitude, route
1, route 2, route 3, route 4, route 5, route 6, route 7, route 8, route
9, route 10, route 11, entry, entrance_type, vending, and ada. These
variables describe the station line, the station name, where the station
is situated on a map, the 11 different routes, vending information, and
information about the station entrances, and ADA compliance.

There were originally other variables in the dataset. I only selected
the variables required, and left out the other variables from the final
data frame. Some of the variables that were cleaned out included
information about division of the stations, staffing hours, and station
exit only information. After extracting and cleaning the variables of
interest, there are 1868 rows and 32 columns in this data frame. I also
recoded the entry variable from a character (YES/NO) variable into a
logical (TRUE/FALSE) variable.

No, the original data import is not tidy. The `route1` through `route11`
variables are all in separate columns instead of being within one column
but separated by row. This means that these columns are values and not
variable names.

*How many distinct stations are there?*

``` r
subway_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

*How many stations are ADA compliant?*

``` r
subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow() 
```

    ## [1] 84

There are 84 stations that are ADA compliant.

*What proportion of station entrances / exits without vending allow
entrance?*

``` r
subway_df |> 
  filter(vending == "NO") |>
  nrow()
```

    ## [1] 183

``` r
subway_df |> 
  filter(entry == TRUE, vending == "NO") |>
  nrow()
```

    ## [1] 69

There are 183 stations without vending. Out of these 183 stations, 69
stations allow entrance.

Reformatting the data so that route number and route name are distinct
variables.

``` r
subway_tidy_df = 
subway_df |>
  mutate(across(c(route8, route9, route10, route11), as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )
```

*How many distinct stations serve the A train?*

``` r
subway_tidy_df |>
  filter(route_name == "A") |>
  distinct(station_name, line) |>
  nrow()
```

    ## [1] 60

60 stations serve the A train.

*Of the stations that serve the A train, how many are ADA compliant?*

``` r
subway_tidy_df |>
  filter(route_name == "A", ada == TRUE) |> 
  distinct(line, station_name) |>
  nrow() 
```

    ## [1] 17

Of the stations that serve the A train, 17 are ADA compliant.

# Problem 2

Read, clean, and name the wheel variables for the Mr Trashwheel dataset.
Also utilize the mutate function to convert character variables to
numeric variables.

``` r
mr_trashwheel_df =
  read_excel(path = "data/202610 Trash Wheel Collection Data.xlsx",
             sheet = "Mr. Trash Wheel",
             range = "A2:N742",
             na = c("", "NA", ".")) |>
  janitor::clean_names() |>
  mutate(sports_balls = as.integer(sports_balls),
         year = as.numeric(year),
         wheel_name = "mr_trash_wheel")
```

Read, clean, and name the wheel variables for the Professor Trashwheel
dataset. Also utilize the mutate function to convert character variables
to numeric variables.

``` r
prof_trashwheel_df = 
  read_excel(path = "data/202610 Trash Wheel Collection Data.xlsx",
             sheet = "Professor Trash Wheel",
             range = "A2:M139",
             na = c("", "NA", ".")) |>
  janitor::clean_names() |>
  mutate(wheel_name = "prof_trash_wheel",
         plastic_bottles = as.numeric(plastic_bottles))
```

Read, clean, and name the wheel variables for the Gwynnda dataset.

``` r
gwyn_trashwheel_df = 
  read_excel(path = "data/202610 Trash Wheel Collection Data.xlsx", 
             sheet = "Gwynnda the Good Wheel of the W", 
             range = "A2:L394",
             na = c("", "NA", ".")) |>
  janitor::clean_names() |>
  mutate(wheel_name = "gwyn_trash_wheel")
```

Now, we combine the datasets.

``` r
trash_wheel_combined = bind_rows(mr_trashwheel_df, prof_trashwheel_df, gwyn_trashwheel_df)
```

Once the three trash wheel datasets were combined, there are now 1269
observations and 15 columns. The variables include `dumpster`, `month`,
`year`, `date`, `weight_tons`, `volume_cubic_yards`, `plastic_bottles`,
`polystyrene`, `cigaretts_butts`, `glass_bottles`, `plastic_bags`,
`wrappers`, `sports_balls`, `homes_powered` and `wheel_name`. The key
variables are essentially the point in time in which the data is
collected, the type of trash collected, and the name of the wheel.

For the available data, the total weight of trash collected by Professor
Trash Wheel is 294.96 tons.

The total number of cigarette butts collected by Gwynda in June of 2022
is 18120.

# Problem 3

Import, clean, and tidy the dataset of baseline characteristics for
Problem 3:

``` r
MCI_baseline_df = 
  read_csv(
    file = "data/MCI_baseline.csv",
    skip = 1, 
    na = c("", "NA", ".")
    ) |> 
  janitor::clean_names() |>
  mutate(
    sex = recode(sex, `1` = "Male", `0` = "Female"),
    apoe4 = recode(apoe4, `1` = "APOE4_carrier", `0` = "APOE4_non-carrier")) |>
  filter(is.na(age_at_onset) | age_at_onset > current_age) 
```

I imported the CSV file into R Studio. I then skipped the first line of
the CSV file since it was details about the codebook. Then, I
standardized the NA variables. I then re coded the `sex` and `apoe4`
variables from numeric into character variables based on the codebook
provided in line 1 of the CSV file. To ensure that participants who do
not meet the stated inclusion criteria (no MBI at baseline) are
excluded, I utilized the filter function to remove participants who had
MCI onset before baseline. I included the NA participants since they
have yet to have a MCI onset.

There are 479 subjects and 6 variables. The variables include `id`,
`current_age`, `sex`, `education`, `apoe4`, and `age_at_onset`. There
were 479 participants who were recruited, of which 93 developed MCI.

The average baseline age is 65.0286013 years.

The proportion of women in the study who is an APOE4 carrier is 63/210
or 0.3.

Importing MCI Amyloid dataset:

``` r
MCI_amyloid_df = 
  read_csv(
    file = "data/mci_amyloid.csv",
    skip = 1, 
    na = c("", "NA", ".")
    ) |> 
  janitor::clean_names() |>
  rename(id = study_id)
```

I imported the CSV file, standardized missing values, and skipped the
first line in the dataset. Similarly to the baseline dataset, I also
skipped the first row of the dataset since it was providing codebook
information. I then renamed the `Study ID` column to `ID` to match the
baseline dataset.

The dataset provides information about the Alzheimer’s biomarker,
amyloid beta 42/40. There are 487 subjects and 6 variables in the
amyloid dataset. The dataset include variables such as `id`, `baseline`,
`time_2`, `time_4`, `time_6`, `time_8`. The timepoints show the
biomarkers present at different points time.

There are 16 participants that appear in the amyloid dataset but not in
the baseline dataset.

There are 8 participants that appear in the baseline dataset but not in
the amyloid dataset.

Now, the two datasets are combined:

``` r
MCI_combined_df = inner_join(MCI_amyloid_df, MCI_baseline_df, by = "id") 
```

There are 471 rows and 11 columns in the combined dataset. Important
variables include `id`, `sex`, `education`, `apoe4`, `current_age`,
`age_at_onset` and biomarker variables at different timepoints including
at baseline.

Exporting Final CSV file:

``` r
write_csv(MCI_combined_df, "data/MCI_combined.csv")
```
